name: generate-project
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: pull image
      run: docker pull miragon/process-ide-cli:0.0.3  
    - name: test file access
      run: docker run miragon/process-ide-cli:0.0.3 node main.js deploy -d example/ -t local