name: generate-project
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3 
    - name: pull image
      run: docker pull miragon/process-ide-cli
    - name: test
      run: ls
    - name: test file access
      run: docker run miragon/process-ide-cli node main.js deploy -d example/ -t local