name: deploy process
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3 
    - name: Deploy process
      uses: miragon/miranum-cli-action@v1
      with: 
        project-directory: './'