name: generat-project
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: miragon/process-ide-cli:0.0.3
    steps: 
    - name: test
      run: ls
    - name: test file access
      run: node main.js deploy -d example/ -t local
